# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 100)
        MainWindow.setMinimumSize(QtCore.QSize(800, 100))
        MainWindow.setMaximumSize(QtCore.QSize(800, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(6, 6, 594, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.start_scraping = QtWidgets.QPushButton(self.centralwidget)
        self.start_scraping.setGeometry(QtCore.QRect(6, 55, 188, 41))
        self.start_scraping.setObjectName("start_scraping")
        self.open_table = QtWidgets.QPushButton(self.centralwidget)
        self.open_table.setGeometry(QtCore.QRect(610, 6, 188, 41))
        self.open_table.setObjectName("open_table")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 60, 251, 28))
        self.label.setObjectName("label")
        self.time_scraping = QtWidgets.QSpinBox(self.centralwidget)
        self.time_scraping.setGeometry(QtCore.QRect(470, 50, 71, 51))
        self.time_scraping.setMinimum(1)
        self.time_scraping.setMaximum(60)
        self.time_scraping.setObjectName("time_scraping")
        self.stop_scraping = QtWidgets.QPushButton(self.centralwidget)
        self.stop_scraping.setEnabled(True)
        self.stop_scraping.setGeometry(QtCore.QRect(587, 55, 211, 41))
        self.stop_scraping.setObjectName("stop_scraping")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Вставьте свой URL..."))
        self.start_scraping.setText(_translate("MainWindow", "Начать скрапинг"))
        self.open_table.setText(_translate("MainWindow", "Открыть таблицу"))
        self.label.setText(_translate("MainWindow", "Время скрапинга (в мин):"))
        self.stop_scraping.setText(_translate("MainWindow", "Закончить скрапинг"))
