# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 100)
        MainWindow.setMinimumSize(QtCore.QSize(800, 100))
        MainWindow.setMaximumSize(QtCore.QSize(800, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(6, 6, 594, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.scraping = QtWidgets.QPushButton(self.centralwidget)
        self.scraping.setGeometry(QtCore.QRect(606, 6, 188, 41))
        self.scraping.setObjectName("scraping")
        self.open_table = QtWidgets.QPushButton(self.centralwidget)
        self.open_table.setGeometry(QtCore.QRect(606, 53, 188, 41))
        self.open_table.setObjectName("open_table")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Вставьте свой URL..."))
        self.scraping.setText(_translate("MainWindow", "Начать скрапинг"))
        self.open_table.setText(_translate("MainWindow", "Открыть таблицу"))
